CFLAGS=-Os -Wall

service:

#install:
#	install -d /usr/local/bin
#	install -t /usr/local/bin service
#	install -d /usr/local/share/man/man1
#	install -t /usr/local/share/man/man1 service.1

clean:
	rm -rf service