
PROGS=fork forkwatch exec execfork open-exec1 open-exec2 signal signal-good signal-better signal-block daemon
CC=gcc
CFLAGS=-Wall -g -std=c99 -D_POSIX_SOURCE
all: ${PROGS}

clean:
	rm -f ${PROGS} *~
